export default {
    ATLASSIAN_JIRA_BASE_URL: process.env.ATLASSIAN_JIRA_BASE_URL || null,
    ATLASSIAN_JIRA_AUTH_ACCESS_TOKEN: process.env.ATLASSIAN_JIRA_AUTH_ACCESS_TOKEN || null,
    ATLASSIAN_JIRA_AUTH_EMAIL_ADDRESS: process.env.ATLASSIAN_JIRA_AUTH_EMAIL_ADDRESS || null,
    ATLASSIAN_JIRA_DATA_OUT_PATH: process.env.ATLASSIAN_JIRA_DATA_OUT_PATH || null,
    ATLASSIAN_JIRA_DATA_OUT_FILE_EXT: process.env.ATLASSIAN_JIRA_DATA_OUT_FILE_EXT || null,
}