export default {
    MONDAY_COM_WORK_MANAGEMENT_BASE_URL: process.env.MONDAY_COM_WORK_MANAGEMENT_BASE_URL || null,
    MONDAY_COM_WORK_MANAGEMENT_AUTH_ACCESS_TOKEN: process.env.MONDAY_COM_WORK_MANAGEMENT_AUTH_ACCESS_TOKEN || null,
    MONDAY_COM_WORK_MANAGEMENT_DATA_OUT_PATH: process.env.MONDAY_COM_WORK_MANAGEMENT_DATA_OUT_PATH || null,
    MONDAY_COM_WORK_MANAGEMENT_DATA_OUT_FILE_EXT: process.env.MONDAY_COM_WORK_MANAGEMENT_DATA_OUT_FILE_EXT || null,
}